from typing import Any

import numpy as np
from numpy.typing import ArrayLike

class NotPositiveDefinite(ValueError): ...

def portfolio_returns(returns: ArrayLike, weights: ArrayLike) -> np.ndarray: ...
def historical_var(pnl: ArrayLike, confidence: float = 0.99) -> dict[str, Any]: ...
def parametric_var(pnl: ArrayLike, confidence: float = 0.99) -> dict[str, Any]: ...
def monte_carlo_var(
    mu: ArrayLike,
    cov: ArrayLike,
    weights: ArrayLike,
    paths: int = 100_000,
    confidence: float = 0.99,
    horizon_days: int = 10,
    seed: int = 42,
    dof: int = 5,
    threads: int = 0,
) -> dict[str, Any]: ...
def backtest_historical_var(pnl: ArrayLike, window: int = 250, confidence: float = 0.99) -> dict[str, Any]: ...
def cholesky(cov: ArrayLike) -> np.ndarray: ...
def norm_ppf(p: float) -> float: ...
def tail_count(n: int, confidence: float) -> int: ...
